### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by arnabmunshi** [bradtraversy/part_manager#2]
```
243 INFO: PyInstaller: 3.5
244 INFO: Python: 3.8.0
247 INFO: Platform: Windows-10-10.0.18362-SP0
250 INFO: wrote D:\Python\part-manager\part_manager.spec
255 INFO: UPX is not available.
270 INFO: Extending PYTHONPATH with paths
['D:\\Python\\part-manager', 'D:\\Python\\part-manager']
270 INFO: checking Analysis
272 INFO: Building Analysis because Analysis-00.toc is non existent
274 INFO: Initializing module dependency graph...
283 INFO: Initializing module graph hooks...
471 INFO: Analyzing base_library.zip ...
31002 INFO: running Analysis Analysis-00.toc
31043 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\wpits\appdata\local\programs\python\python38-32\python.exe
34258 INFO: Caching module hooks...
34569 INFO: Analyzing D:\Python\part-manager\part_manager.py
35341 INFO: Loading module hooks...
35342 INFO: Loading module hook "hook-encodings.py"...
35771 INFO: Loading module hook "hook-pydoc.py"...
35848 INFO: Loading module hook "hook-sqlite3.py"...
36213 INFO: Loading module hook "hook-xml.py"...
37755 INFO: Loading module hook "hook-_tkinter.py"...
38461 INFO: checking Tree
38462 INFO: Building Tree because Tree-00.toc is non existent
38464 INFO: Building Tree Tree-00.toc
39531 INFO: checking Tree
39532 INFO: Building Tree because Tree-01.toc is non existent
39535 INFO: Building Tree Tree-01.toc
39795 INFO: Looking for ctypes DLLs
39815 INFO: Analyzing run-time hooks ...
39829 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
39977 INFO: Including run-time hook 'pyi_rth__tkinter.py'
40052 INFO: Looking for dynamic libraries
52244 INFO: Looking for eggs
52245 INFO: Using Python library c:\users\wpits\appdata\local\programs\python\python38-32\python38.dll
52247 INFO: Found binding redirects:
[]
52266 INFO: Warnings written to D:\Python\part-manager\build\part_manager\warn-part_manager.txt
52518 INFO: Graph cross-reference written to D:\Python\part-manager\build\part_manager\xref-part_manager.html
52802 INFO: checking PYZ
52803 INFO: Building PYZ because PYZ-00.toc is non existent
52808 INFO: Building PYZ (ZlibArchive) D:\Python\part-manager\build\part_manager\PYZ-00.pyz
Traceback (most recent call last):
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\WPITS\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "D:\Python\part-manager\part_manager.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\wpits\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
```

**Comment by arnabmunshi** [comment]
I have found the way to fix the error.

First run this command
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz`

Then run this command
`pyinstaller --onefile -w part_manager.py`

Thanx @bradtraversy for that wonderful tutorial :)
